# SPDX-FileCopyrightText: 2024 Semiotic Labs
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    groups:
      # Group minor and patch updates together
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Group major updates separately for careful review
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
      # Group security updates with high priority
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    groups:
      docker-updates:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
