repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      # Format code with rustfmt
      - id: fmt
        args: ["--all", "--"]

      # Check with clippy
      - id: clippy
        args: ["--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]

      # Run cargo check
      - id: cargo-check
        args: ["--workspace", "--all-targets", "--all-features"]
  - repo: local
    hooks:
      - id: reuse-annotate
        name: REUSE License Annotation
        entry: bash -c 'reuse lint || (echo -e "❌ REUSE annotation failed, try running:\nannotate --license Apache-2.0 --copyright "Semiotic Labs" --year 2025 -r . --skip-unrecognized --skip-existing" && exit 1')
        language: system
        pass_filenames: false
        always_run: true

      # Check licenses and dependencies
      - id: cargo-deny
        name: cargo-deny
        entry: cargo deny check
        language: system
        types: [rust]
        pass_filenames: false
