[graph]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]
all-features = true

[advisories]
unmaintained = "workspace"
ignore = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "Zlib",
  "CC0-1.0",
  "CDLA-Permissive-2.0"
]

[bans]
allow = []
external-default-features = "allow"
multiple-versions = "warn"
deny = [
  { crate = "git2", use-instead = "gix" },
  { crate = "openssl", use-instead = "rustls" },
  { crate = "openssl-sys", use-instead = "rustls" },
  "libssh2-sys",
  { crate = "cmake", use-instead = "cc" },
  { crate = "windows", reason = "bloated and unnecessary", use-instead = "ideally inline bindings, practically, windows-sys" },
]
