// SPDX-FileCopyrightText: 2025 Semiotic Labs
//
// SPDX-License-Identifier: Apache-2.0

//! API documentation module
//!
//! This module provides `OpenAPI` documentation configuration using utoipa.
//! It defines the complete API specification including endpoints, schemas,
//! and metadata for interactive documentation.

#![allow(clippy::needless_for_each)] // Generated by OpenApi derive macro

use shared_types::{ChainId, ChainImplementationStatus};
use utoipa::OpenApi;

use crate::{
    routes::handlers::{
        ChainInfo, ChainsResponse, ContractStatusRequest, ContractStatusResponse,
        ContractStatusResult,
    },
    state::{HealthCheck, HealthStatus},
};

/// `OpenAPI` documentation specification
#[derive(OpenApi, Debug)]
#[openapi(
    info(
        title = "NFT API Service",
        description = "A secure blockchain token management API service for NFT spam detection analysis with comprehensive multi-chain support.\n\n**Supported Blockchain Networks:**\n- Ethereum Mainnet (Chain ID: 1)\n- Polygon (Chain ID: 137)\n- Base (Chain ID: 8453)\n- Avalanche C-Chain (Chain ID: 43114)\n- Arbitrum One (Chain ID: 42161)\n\n**Features:**\n- AI-powered spam classification using fine-tuned GPT models\n- Multi-chain architecture with chain-specific data sources\n- External blockchain data integration (Moralis API, Pinax Analytics)\n- Chain-specific capability validation and error handling\n- Built-in rate limiting with chain-aware middleware\n- Comprehensive health monitoring with chain status reporting\n- Detailed chain validation with informative error messages\n\n**Chain-Specific Data Sources:**\n- Moralis API: NFT metadata and contract information for all chains\n- Pinax Analytics: Blockchain analytics with chain-specific databases\n- AI Spam Predictor: Chain-agnostic spam classification\n\n**Rate Limiting:**\nAPI endpoints are rate limited with chain-specific tracking.\n\n**API Versioning:**\nThis API uses URL-based versioning. Current version is v1. All contract analysis endpoints are prefixed with `/v1/`.\n\n**Error Handling:**\nAPI provides detailed error responses with chain-specific context and validation messages.",
        version = "0.1.0",
        contact(
            name = "Semiotic Labs",
            url = "https://github.com/semiotic-ai/nft-api"
        ),
        license(
            name = "Apache-2.0",
            url = "https://www.apache.org/licenses/LICENSE-2.0"
        )
    ),
    servers(
        (url = "/", description = "Local server")
    ),
    paths(
        crate::routes::handlers::health_handler,
        crate::routes::handlers::chains_handler,
        crate::routes::handlers::contract_status_handler,
    ),
    components(
        schemas(
            ChainId,
            ChainInfo,
            ChainImplementationStatus,
            ChainsResponse,
            ContractStatusRequest,
            ContractStatusResponse,
            ContractStatusResult,
            HealthCheck,
            HealthStatus,
        )
    ),
    tags(
        (name = "health", description = "System health monitoring - Check API service status, external API client health, chain-specific configurations, and internal service availability. Includes comprehensive chain health reporting with capability validation. Used for monitoring, alerting, and chain status verification."),
        (name = "chains", description = "Blockchain network information - Provides information about all supported blockchain networks and their capabilities."),
        (name = "contracts", description = "Multi-chain blockchain contract analysis - AI-powered spam detection for NFT contracts across Ethereum, Polygon, Base, Avalanche, and Arbitrum networks. Utilizes chain-specific external data sources (Moralis API, Pinax Analytics) with intelligent capability validation and comprehensive error handling. Supports batch analysis and provides detailed chain-specific response messages.")
    )
)]
pub struct ApiDoc;
