// SPDX-FileCopyrightText: 2025 Semiotic Labs
//
// SPDX-License-Identifier: Apache-2.0

//! API documentation module
//!
//! This module provides `OpenAPI` documentation configuration using utoipa.
//! It defines the complete API specification including endpoints, schemas,
//! and metadata for interactive documentation.

#![allow(clippy::needless_for_each)] // Generated by OpenApi derive macro

use shared_types::{ChainId, ChainImplementationStatus};
use utoipa::OpenApi;

use crate::{
    routes::handlers::{ContractStatusRequest, ContractStatusResponse, ContractStatusResult},
    state::{HealthCheck, HealthStatus},
};

/// `OpenAPI` documentation specification
#[derive(OpenApi, Debug)]
#[openapi(
    info(
        title = "NFT API Service",
        description = "A blockchain token management API service for NFT spam detection analysis.",
        version = "0.1.0",
        contact(
            name = "Semiotic Labs",
            url = "https://github.com/semiotic-ai/nft-api"
        ),
        license(
            name = "Apache-2.0",
            url = "https://www.apache.org/licenses/LICENSE-2.0"
        )
    ),
    servers(
        (url = "/", description = "Local server")
    ),
    paths(
        crate::routes::handlers::health_handler,
        crate::routes::handlers::contract_status_handler,
    ),
    components(
        schemas(
            ChainId,
            ChainImplementationStatus,
            ContractStatusRequest,
            ContractStatusResponse,
            ContractStatusResult,
            HealthCheck,
            HealthStatus,
        )
    ),
    tags(
        (name = "health", description = "Health check endpoints"),
        (name = "contracts", description = "Contract analysis and spam detection endpoints")
    )
)]
pub struct ApiDoc;
