// SPDX-FileCopyrightText: 2025 Semiotic Labs
//
// SPDX-License-Identifier: Apache-2.0

//! API documentation module
//!
//! This module provides `OpenAPI` documentation configuration using utoipa.
//! It defines the complete API specification including endpoints, schemas,
//! and metadata for interactive documentation.

#![allow(clippy::needless_for_each)] // Generated by OpenApi derive macro

use shared_types::{ChainId, ChainImplementationStatus};
use utoipa::OpenApi;

use crate::{
    routes::handlers::{ContractStatusRequest, ContractStatusResponse, ContractStatusResult},
    state::{HealthCheck, HealthStatus},
};

/// `OpenAPI` documentation specification
#[derive(OpenApi, Debug)]
#[openapi(
    info(
        title = "NFT API Service",
        description = "A secure blockchain token management API service for NFT spam detection analysis. \n\n**Features:**\n- AI-powered spam classification using fine-tuned GPT models\n- Multi-chain support\n- External blockchain data integration (Moralis, Pinax)\n- Built-in rate limiting\n- Comprehensive health monitoring\n\n**Rate Limiting:**\nAPI endpoints are rate limited.\n\n**API Versioning:**\nThis API uses URL-based versioning. Current version is v1. All contract analysis endpoints are prefixed with `/v1/`.",
        version = "0.1.0",
        contact(
            name = "Semiotic Labs",
            url = "https://github.com/semiotic-ai/nft-api"
        ),
        license(
            name = "Apache-2.0",
            url = "https://www.apache.org/licenses/LICENSE-2.0"
        )
    ),
    servers(
        (url = "/", description = "Local server")
    ),
    paths(
        crate::routes::handlers::health_handler,
        crate::routes::handlers::contract_status_handler,
    ),
    components(
        schemas(
            ChainId,
            ChainImplementationStatus,
            ContractStatusRequest,
            ContractStatusResponse,
            ContractStatusResult,
            HealthCheck,
            HealthStatus,
        )
    ),
    tags(
        (name = "health", description = "System health monitoring - Check API service status, external API client health, and internal service availability. Used for monitoring and alerting."),
        (name = "contracts", description = "Blockchain contract analysis - AI-powered spam detection for NFT contracts using external blockchain data sources. Supports multiple chains with rate limiting.")
    )
)]
pub struct ApiDoc;
